# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('assoc_job', models.OneToOneField(default=b'0000', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='associd', serialize=False, to='upload.Upload')),
                ('json', models.FileField(null=True, upload_to=b'')),
                ('graph', models.TextField(null=True)),
            ],
        ),
    ]
