# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='json',
            new_name='json_data',
        ),
    ]
