# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d3', '0002_auto_20160324_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='graph',
        ),
        migrations.AddField(
            model_name='graph',
            name='positions',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
