# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20160331_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='attributes',
            field=models.PositiveSmallIntegerField(choices=[(b'10', b'10'), (b'50', b'50'), (b'100', b'100'), (b'200', b'200')], default=100),
        ),
        migrations.AddField(
            model_name='upload',
            name='biohel_runs',
            field=models.PositiveSmallIntegerField(choices=[(b'250', b'250'), (b'500', b'500'), (b'1000', b'1000'), (b'2500', b'2500')], default=1000),
        ),
        migrations.AddField(
            model_name='upload',
            name='permutations',
            field=models.PositiveSmallIntegerField(choices=[(b'10', b'10'), (b'50', b'50'), (b'100', b'100'), (b'200', b'200')], default=100),
        ),
        migrations.AddField(
            model_name='upload',
            name='setting',
            field=models.PositiveSmallIntegerField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4')], default=1),
        ),
    ]
