# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20160419_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='attributes',
            field=models.PositiveSmallIntegerField(choices=[(10, b'10'), (50, b'50'), (100, b'100'), (200, b'200')], default=10),
        ),
        migrations.AlterField(
            model_name='upload',
            name='biohel_runs',
            field=models.PositiveSmallIntegerField(choices=[(2, b'2'), (250, b'250'), (500, b'500'), (1000, b'1000'), (2500, b'2500')], default=2),
        ),
        migrations.AlterField(
            model_name='upload',
            name='permutations',
            field=models.PositiveSmallIntegerField(choices=[(10, b'10'), (50, b'50'), (100, b'100'), (200, b'200')], default=10),
        ),
        migrations.AlterField(
            model_name='upload',
            name='setting',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4')], default=1),
        ),
    ]
