# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20160421_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='biohel_runs',
            field=models.PositiveSmallIntegerField(choices=[(2, b'2'), (15, b'15'), (250, b'250'), (500, b'500'), (1000, b'1000'), (2500, b'2500')], default=2),
        ),
        migrations.AlterField(
            model_name='upload',
            name='permutations',
            field=models.PositiveSmallIntegerField(choices=[(10, b'10'), (15, b'15'), (50, b'50'), (100, b'100'), (200, b'200')], default=10),
        ),
    ]
