# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20160430_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
